### ISSUE TITLE
Stream model

### ISSUE THREAD

**Issue by papyr** [KingKnecht/FlatStreamToHierarchy#6]
Hi, I am trying to apply this to my own scenario, cna you help guide me on what the the stream and hierarchy structures should like like, so I can follow some steps to set it up.

thanks
Papi

**Comment by KingKnecht** [comment]
I suggest to have a look at EmployeeDto and EmployeeService first.
EmployeeService provides a stream of EmployeeDtos.
Each EmployeeDto has an ID to its boss. So we have a hierachy defined by boss-Ids. (and not by references).
Maybe you want to debug the app a little bit so see what's going on.
Let me know if you have any question.

DTO = Data transfer object, other word for some poco class moved around....

**Comment by papyr** [comment]
ok will try thanks :+1:
